/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TransactionType = IDL.Variant({
  'expense' : IDL.Null,
  'income' : IDL.Null,
});
export const Frequency = IDL.Variant({
  'monthly' : IDL.Null,
  'yearly' : IDL.Null,
  'daily' : IDL.Null,
  'weekly' : IDL.Null,
});
export const Time = IDL.Int;
export const RecurringTransaction = IDL.Record({
  'id' : IDL.Nat,
  'active' : IDL.Bool,
  'transactionType' : TransactionType,
  'endDate' : IDL.Opt(Time),
  'description' : IDL.Text,
  'lastPeriodicExecution' : Time,
  'category' : IDL.Text,
  'frequency' : Frequency,
  'amount' : IDL.Nat,
  'lastExecutionDate' : Time,
  'startDate' : Time,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'transactionType' : TransactionType,
  'description' : IDL.Text,
  'timestamp' : Time,
  'category' : IDL.Text,
  'amount' : IDL.Nat,
});
export const BudgetLimit = IDL.Record({
  'limit' : IDL.Nat,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'addBudgetLimit' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'addRecurringTransaction' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        TransactionType,
        Frequency,
        Time,
        IDL.Opt(Time),
      ],
      [IDL.Nat],
      [],
    ),
  'addTransaction' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, TransactionType],
      [IDL.Nat],
      [],
    ),
  'deleteBudgetLimit' : IDL.Func([IDL.Text], [], []),
  'deleteRecurringTransaction' : IDL.Func([IDL.Nat], [], []),
  'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
  'getAllRecurringTransactions' : IDL.Func(
      [],
      [IDL.Vec(RecurringTransaction)],
      ['query'],
    ),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getExpenseCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getExpenses' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getIncome' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getIncomeCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getTransactionsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getTransactionsByType' : IDL.Func(
      [TransactionType],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getUserBudgetLimitsQuery' : IDL.Func([], [IDL.Vec(BudgetLimit)], ['query']),
  'getUserRecurringTransactionsQuery' : IDL.Func(
      [],
      [IDL.Vec(RecurringTransaction)],
      ['query'],
    ),
  'getUserTransactionsQuery' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'processRecurringTransactions' : IDL.Func([], [], []),
  'toggleRecurringTransactionActive' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'updateRecurringTransaction' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        TransactionType,
        Frequency,
        Time,
        IDL.Opt(Time),
      ],
      [],
      [],
    ),
  'updateTransaction' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TransactionType = IDL.Variant({
    'expense' : IDL.Null,
    'income' : IDL.Null,
  });
  const Frequency = IDL.Variant({
    'monthly' : IDL.Null,
    'yearly' : IDL.Null,
    'daily' : IDL.Null,
    'weekly' : IDL.Null,
  });
  const Time = IDL.Int;
  const RecurringTransaction = IDL.Record({
    'id' : IDL.Nat,
    'active' : IDL.Bool,
    'transactionType' : TransactionType,
    'endDate' : IDL.Opt(Time),
    'description' : IDL.Text,
    'lastPeriodicExecution' : Time,
    'category' : IDL.Text,
    'frequency' : Frequency,
    'amount' : IDL.Nat,
    'lastExecutionDate' : Time,
    'startDate' : Time,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'transactionType' : TransactionType,
    'description' : IDL.Text,
    'timestamp' : Time,
    'category' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const BudgetLimit = IDL.Record({ 'limit' : IDL.Nat, 'category' : IDL.Text });
  
  return IDL.Service({
    'addBudgetLimit' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'addRecurringTransaction' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          TransactionType,
          Frequency,
          Time,
          IDL.Opt(Time),
        ],
        [IDL.Nat],
        [],
      ),
    'addTransaction' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, TransactionType],
        [IDL.Nat],
        [],
      ),
    'deleteBudgetLimit' : IDL.Func([IDL.Text], [], []),
    'deleteRecurringTransaction' : IDL.Func([IDL.Nat], [], []),
    'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
    'getAllRecurringTransactions' : IDL.Func(
        [],
        [IDL.Vec(RecurringTransaction)],
        ['query'],
      ),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getExpenseCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getExpenses' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getIncome' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getIncomeCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getTransactionsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getTransactionsByType' : IDL.Func(
        [TransactionType],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getUserBudgetLimitsQuery' : IDL.Func(
        [],
        [IDL.Vec(BudgetLimit)],
        ['query'],
      ),
    'getUserRecurringTransactionsQuery' : IDL.Func(
        [],
        [IDL.Vec(RecurringTransaction)],
        ['query'],
      ),
    'getUserTransactionsQuery' : IDL.Func(
        [],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'processRecurringTransactions' : IDL.Func([], [], []),
    'toggleRecurringTransactionActive' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'updateRecurringTransaction' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          TransactionType,
          Frequency,
          Time,
          IDL.Opt(Time),
        ],
        [],
        [],
      ),
    'updateTransaction' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };