/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BudgetLimit { 'limit' : bigint, 'category' : string }
export type Frequency = { 'monthly' : null } |
  { 'yearly' : null } |
  { 'daily' : null } |
  { 'weekly' : null };
export interface RecurringTransaction {
  'id' : bigint,
  'active' : boolean,
  'transactionType' : TransactionType,
  'endDate' : [] | [Time],
  'description' : string,
  'lastPeriodicExecution' : Time,
  'category' : string,
  'frequency' : Frequency,
  'amount' : bigint,
  'lastExecutionDate' : Time,
  'startDate' : Time,
}
export type Time = bigint;
export interface Transaction {
  'id' : bigint,
  'transactionType' : TransactionType,
  'description' : string,
  'timestamp' : Time,
  'category' : string,
  'amount' : bigint,
}
export type TransactionType = { 'expense' : null } |
  { 'income' : null };
export interface _SERVICE {
  'addBudgetLimit' : ActorMethod<[string, bigint], undefined>,
  'addRecurringTransaction' : ActorMethod<
    [string, bigint, string, TransactionType, Frequency, Time, [] | [Time]],
    bigint
  >,
  'addTransaction' : ActorMethod<
    [bigint, string, string, TransactionType],
    bigint
  >,
  'deleteBudgetLimit' : ActorMethod<[string], undefined>,
  'deleteRecurringTransaction' : ActorMethod<[bigint], undefined>,
  'deleteTransaction' : ActorMethod<[bigint], undefined>,
  'getAllRecurringTransactions' : ActorMethod<[], Array<RecurringTransaction>>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getExpenseCategories' : ActorMethod<[], Array<string>>,
  'getExpenses' : ActorMethod<[], Array<Transaction>>,
  'getIncome' : ActorMethod<[], Array<Transaction>>,
  'getIncomeCategories' : ActorMethod<[], Array<string>>,
  'getTransactionsByCategory' : ActorMethod<[string], Array<Transaction>>,
  'getTransactionsByType' : ActorMethod<[TransactionType], Array<Transaction>>,
  'getUserBudgetLimitsQuery' : ActorMethod<[], Array<BudgetLimit>>,
  'getUserRecurringTransactionsQuery' : ActorMethod<
    [],
    Array<RecurringTransaction>
  >,
  'getUserTransactionsQuery' : ActorMethod<[], Array<Transaction>>,
  'processRecurringTransactions' : ActorMethod<[], undefined>,
  'toggleRecurringTransactionActive' : ActorMethod<[bigint], boolean>,
  'updateRecurringTransaction' : ActorMethod<
    [
      bigint,
      string,
      bigint,
      string,
      TransactionType,
      Frequency,
      Time,
      [] | [Time],
    ],
    undefined
  >,
  'updateTransaction' : ActorMethod<
    [bigint, bigint, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];