/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RecurringTransaction {
    id: bigint;
    active: boolean;
    transactionType: TransactionType;
    endDate?: Time;
    description: string;
    lastPeriodicExecution: Time;
    category: string;
    frequency: Frequency;
    amount: bigint;
    lastExecutionDate: Time;
    startDate: Time;
}
export type Time = bigint;
export interface BudgetLimit {
    limit: bigint;
    category: string;
}
export interface Transaction {
    id: bigint;
    transactionType: TransactionType;
    description: string;
    timestamp: Time;
    category: string;
    amount: bigint;
}
export enum Frequency {
    monthly = "monthly",
    yearly = "yearly",
    daily = "daily",
    weekly = "weekly"
}
export enum TransactionType {
    expense = "expense",
    income = "income"
}
export interface backendInterface {
    addBudgetLimit(category: string, limit: bigint): Promise<void>;
    addRecurringTransaction(category: string, amount: bigint, description: string, transactionType: TransactionType, frequency: Frequency, startDate: Time, endDate: Time | null): Promise<bigint>;
    addTransaction(amount: bigint, category: string, description: string, transactionType: TransactionType): Promise<bigint>;
    deleteBudgetLimit(category: string): Promise<void>;
    deleteRecurringTransaction(id: bigint): Promise<void>;
    deleteTransaction(id: bigint): Promise<void>;
    getAllRecurringTransactions(): Promise<Array<RecurringTransaction>>;
    getAllTransactions(): Promise<Array<Transaction>>;
    getExpenseCategories(): Promise<Array<string>>;
    getExpenses(): Promise<Array<Transaction>>;
    getIncome(): Promise<Array<Transaction>>;
    getIncomeCategories(): Promise<Array<string>>;
    getTransactionsByCategory(category: string): Promise<Array<Transaction>>;
    getTransactionsByType(transactionType: TransactionType): Promise<Array<Transaction>>;
    getUserBudgetLimitsQuery(): Promise<Array<BudgetLimit>>;
    getUserRecurringTransactionsQuery(): Promise<Array<RecurringTransaction>>;
    getUserTransactionsQuery(): Promise<Array<Transaction>>;
    processRecurringTransactions(): Promise<void>;
    toggleRecurringTransactionActive(id: bigint): Promise<boolean>;
    updateRecurringTransaction(id: bigint, category: string, amount: bigint, description: string, transactionType: TransactionType, frequency: Frequency, startDate: Time, endDate: Time | null): Promise<void>;
    updateTransaction(id: bigint, amount: bigint, category: string, description: string): Promise<void>;
}
import type { Frequency as _Frequency, RecurringTransaction as _RecurringTransaction, Time as _Time, Transaction as _Transaction, TransactionType as _TransactionType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addBudgetLimit(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBudgetLimit(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBudgetLimit(arg0, arg1);
            return result;
        }
    }
    async addRecurringTransaction(arg0: string, arg1: bigint, arg2: string, arg3: TransactionType, arg4: Frequency, arg5: Time, arg6: Time | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addRecurringTransaction(arg0, arg1, arg2, to_candid_TransactionType_n1(this._uploadFile, this._downloadFile, arg3), to_candid_Frequency_n3(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRecurringTransaction(arg0, arg1, arg2, to_candid_TransactionType_n1(this._uploadFile, this._downloadFile, arg3), to_candid_Frequency_n3(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async addTransaction(arg0: bigint, arg1: string, arg2: string, arg3: TransactionType): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(arg0, arg1, arg2, to_candid_TransactionType_n1(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(arg0, arg1, arg2, to_candid_TransactionType_n1(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async deleteBudgetLimit(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBudgetLimit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBudgetLimit(arg0);
            return result;
        }
    }
    async deleteRecurringTransaction(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRecurringTransaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRecurringTransaction(arg0);
            return result;
        }
    }
    async deleteTransaction(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTransaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTransaction(arg0);
            return result;
        }
    }
    async getAllRecurringTransactions(): Promise<Array<RecurringTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRecurringTransactions();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRecurringTransactions();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTransactions();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTransactions();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpenseCategories(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpenseCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpenseCategories();
            return result;
        }
    }
    async getExpenses(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpenses();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpenses();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIncome(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncome();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncome();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIncomeCategories(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncomeCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncomeCategories();
            return result;
        }
    }
    async getTransactionsByCategory(arg0: string): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionsByCategory(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionsByCategory(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionsByType(arg0: TransactionType): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionsByType(to_candid_TransactionType_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionsByType(to_candid_TransactionType_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserBudgetLimitsQuery(): Promise<Array<BudgetLimit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserBudgetLimitsQuery();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserBudgetLimitsQuery();
            return result;
        }
    }
    async getUserRecurringTransactionsQuery(): Promise<Array<RecurringTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserRecurringTransactionsQuery();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserRecurringTransactionsQuery();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserTransactionsQuery(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserTransactionsQuery();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserTransactionsQuery();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async processRecurringTransactions(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.processRecurringTransactions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processRecurringTransactions();
            return result;
        }
    }
    async toggleRecurringTransactionActive(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleRecurringTransactionActive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleRecurringTransactionActive(arg0);
            return result;
        }
    }
    async updateRecurringTransaction(arg0: bigint, arg1: string, arg2: bigint, arg3: string, arg4: TransactionType, arg5: Frequency, arg6: Time, arg7: Time | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRecurringTransaction(arg0, arg1, arg2, arg3, to_candid_TransactionType_n1(this._uploadFile, this._downloadFile, arg4), to_candid_Frequency_n3(this._uploadFile, this._downloadFile, arg5), arg6, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRecurringTransaction(arg0, arg1, arg2, arg3, to_candid_TransactionType_n1(this._uploadFile, this._downloadFile, arg4), to_candid_Frequency_n3(this._uploadFile, this._downloadFile, arg5), arg6, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async updateTransaction(arg0: bigint, arg1: bigint, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTransaction(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTransaction(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_Frequency_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Frequency): Frequency {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_RecurringTransaction_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecurringTransaction): RecurringTransaction {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    transactionType: _TransactionType;
    description: string;
    timestamp: _Time;
    category: string;
    amount: bigint;
}): {
    id: bigint;
    transactionType: TransactionType;
    description: string;
    timestamp: Time;
    category: string;
    amount: bigint;
} {
    return {
        id: value.id,
        transactionType: from_candid_TransactionType_n9(_uploadFile, _downloadFile, value.transactionType),
        description: value.description,
        timestamp: value.timestamp,
        category: value.category,
        amount: value.amount
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    active: boolean;
    transactionType: _TransactionType;
    endDate: [] | [_Time];
    description: string;
    lastPeriodicExecution: _Time;
    category: string;
    frequency: _Frequency;
    amount: bigint;
    lastExecutionDate: _Time;
    startDate: _Time;
}): {
    id: bigint;
    active: boolean;
    transactionType: TransactionType;
    endDate?: Time;
    description: string;
    lastPeriodicExecution: Time;
    category: string;
    frequency: Frequency;
    amount: bigint;
    lastExecutionDate: Time;
    startDate: Time;
} {
    return {
        id: value.id,
        active: value.active,
        transactionType: from_candid_TransactionType_n9(_uploadFile, _downloadFile, value.transactionType),
        endDate: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.endDate)),
        description: value.description,
        lastPeriodicExecution: value.lastPeriodicExecution,
        category: value.category,
        frequency: from_candid_Frequency_n12(_uploadFile, _downloadFile, value.frequency),
        amount: value.amount,
        lastExecutionDate: value.lastExecutionDate,
        startDate: value.startDate
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expense: null;
} | {
    income: null;
}): TransactionType {
    return "expense" in value ? TransactionType.expense : "income" in value ? TransactionType.income : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    monthly: null;
} | {
    yearly: null;
} | {
    daily: null;
} | {
    weekly: null;
}): Frequency {
    return "monthly" in value ? Frequency.monthly : "yearly" in value ? Frequency.yearly : "daily" in value ? Frequency.daily : "weekly" in value ? Frequency.weekly : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RecurringTransaction>): Array<RecurringTransaction> {
    return value.map((x)=>from_candid_RecurringTransaction_n7(_uploadFile, _downloadFile, x));
}
function to_candid_Frequency_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Frequency): _Frequency {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): _TransactionType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): {
    expense: null;
} | {
    income: null;
} {
    return value == TransactionType.expense ? {
        expense: null
    } : value == TransactionType.income ? {
        income: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Frequency): {
    monthly: null;
} | {
    yearly: null;
} | {
    daily: null;
} | {
    weekly: null;
} {
    return value == Frequency.monthly ? {
        monthly: null
    } : value == Frequency.yearly ? {
        yearly: null
    } : value == Frequency.daily ? {
        daily: null
    } : value == Frequency.weekly ? {
        weekly: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
